apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app-v1
  labels:
    app: canary-app
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary-app
      version: v1
  template:
    metadata:
      labels:
        app: canary-app
        version: v1
    spec:
      containers:
      - name: canary-app
        image: canary-app:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: canary-app-v1
  labels:
    app: canary-app
    version: v1
spec:
  selector:
    app: canary-app
    version: v1
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
